// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Timetracker.Infrastructure.Context;

#nullable disable

namespace Timetracker.Infrastructure.Migrations
{
    [DbContext(typeof(TimetrackerDbContext))]
    partial class TimetrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Timetracker.Infrastructure.Entities.AppSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultMetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PromptOnStop")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("AppSettingsEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ModifiedAt = new DateTimeOffset(new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            PromptOnStop = true
                        });
                });

            modelBuilder.Entity("Timetracker.Infrastructure.Entities.EntryDescriptionEntity", b =>
                {
                    b.Property<Guid>("TimeEntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonData")
                        .HasColumnType("TEXT");

                    b.HasKey("TimeEntryId");

                    b.HasIndex("TimeEntryId")
                        .IsUnique();

                    b.ToTable("EntryDescriptions");
                });

            modelBuilder.Entity("Timetracker.Infrastructure.Entities.TimeEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("End")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("Timetracker.Infrastructure.Entities.EntryDescriptionEntity", b =>
                {
                    b.HasOne("Timetracker.Infrastructure.Entities.TimeEntryEntity", "TimeEntry")
                        .WithOne("Description")
                        .HasForeignKey("Timetracker.Infrastructure.Entities.EntryDescriptionEntity", "TimeEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeEntry");
                });

            modelBuilder.Entity("Timetracker.Infrastructure.Entities.TimeEntryEntity", b =>
                {
                    b.Navigation("Description");
                });
#pragma warning restore 612, 618
        }
    }
}
